###admin login
POST https://blogapp-xz5w.onrender.com/auth/login
Content-Type: application/json

{
    "email":"admin@mail.com",
    "password":"admin"
}

###read all users & authors(email)
GET https://blogapp-xz5w.onrender.com/admin-api/users


###block user or author
PUT https://blogapp-xz5w.onrender.com/admin-api/user/69b3c80a0aae7f044625f432
Content-Type: application/json

{
  "status": "BLOCKED"
}

###activate user or author
PUT https://blogapp-xz5w.onrender.com/auth/user/USER_ID_HERE/status
Content-Type: application/json

{
  "status": "ACTIVE"
}