###register author
POST https://blogapp-xz5w.onrender.com/auth/users
Content-Type: application/json

{
    "firstName":"author3",
    "lastName":"",
    "email":"author3@mail.com",
    "role":"AUTHOR",
    "password":"author3",
    "profileImageUrl":""
}


###login
POST https://blogapp-xz5w.onrender.com/auth/login
Content-Type:  application/json

{
    "email":"author3@mail.com",
    "password":"author3"
}

###create new article
POST https://blogapp-xz5w.onrender.com/author-api/article
Content-Type: application/json

{
    "author":"69b3c80a0aae7f044625f432",
    "title":"Article-1 by Author 3 ",
    "category":"AIML",
    "content":"test article on AIML"
}


###read own articles
GET https://blogapp-xz5w.onrender.com/author-api/articles


###logout
GET https://blogapp-xz5w.onrender.com/auth/logout


###update article
PUT https://blogapp-xz5w.onrender.com/author-api/articles
Content-Type: application/json

{
    "articleId":"69b3acd0ed84519bc71a85d6",
    "title":"Article-2 by Author 1",
    "category":"AI",
    "content":"test article on AI and its updated"
}


###delete article and restore by article id(soft delete)
PATCH https://blogapp-xz5w.onrender.com/author-api/articles
Content-Type: application/json

{
    "articleId":"69b3acd0ed84519bc71a85d6",
    "isArticleActive":true
}